### PR TITLE
Remove designate and other unused services

### PR DESCRIPTION
**Pull request by hardys**
There are several unused services (most are already disabled by the environments/standalone.yaml and/or overcloud-resource-registry-puppet.j2.yaml), and designate is broken atm due to some changes to the environments in t-h-t, so disable that for now since we're not currently using it.

Closes: https://github.com/imain/ocp-doit/issues/8

### CODE REVIEW

**Comment by hardys** [comment]
@tomassedovic this works OK for me locally (only tested updating an existing standalone env but I can't see any reason it won't work on a fresh deploy as well).

@celebdor - does this align with what you tested last week?

**Comment by tomassedovic** [comment]
@hardys how far did you test this?

The actual undercloud installation succeeded for me and I was able to run openshift-install successfully. But the resulting VMs are not able to ping google.com (or any other external domain name).

Same was true with the cirros test VM.

And this leads into docker image pull errors in bootkube.sh.

**Comment by tomassedovic** [comment]
I'll try and redeploy it again -- maybe Neutron DNS didn't come up properly or something. But I was wondering whether you got past that on your end.

**Comment by tomassedovic** [comment]
So I don't know why yet, but the `DNS_SERVER_1` and `DNS_SERVER_2` config entries are not used anymore. They should be added to `dnsmasq_dns_servers` in:

`/var/lib/config-data/puppet-generated/neutron/etc/neutron/dhcp_agent.ini`

but that entry is empty. When I've added the DNS to my bootstrap node's `/etc/resolv.conf`, it started working again. Any chance one of the deleted roles should actually stay?

**Comment by hardys** [comment]
@tomassedovic things seemed to work for me but I tested only update of an existing environment.

Can you share the exact steps e.g shell history for the cirros test and I'll try to reproduce?

**Comment by hardys** [comment]
@tomassedovic I think this may be related again to openstack/tripleo-heat-templates@3abb38a since before that the enable_designate environment set NeutronEnableInternalDNS: True which meant we resolved via designate/neutron?

If I'm right about that, you should see the same issue without this patch, just by rebasing your t-h-t to the latest version?

The fix, I think, is to manually set NeutronDhcpAgentDnsmasqDnsServers to consume DNS_SERVER_1 and DNS_SERVER_2 in the $SCRIPTDIR/standalone_parameters.yaml - I'll update the patch to do that and re-test

**Comment by hardys** [comment]
One point of confusion is the DnsServers parameter is already set, so I'm wondering why we need to set NeutronDhcpAgentDnsmasqDnsServers which is related to dnsmasq forwarders.

That parameter was added via https://review.openstack.org/#/c/422898/ and I'm wondering if we should add a heat conditional so when not set it defaults to DnsServers?

Maybe @cybertron can help us figure that out if he's not too upset that we're temporarily disabling designate here ;)

**Comment by cybertron** [comment]
What?! Heresy! :-)

Note that DnsServers is only applicable to the cloud baremetal systems. Overcloud neutron networks have their own DNS settings, which by default point to Neutron internal dns. If you were relying on the Designate enablement of internal dns and the deployment wasn't updated to include the new config template then that could very well explain why your VMs can't get DNS. Unfortunately Neutron internal DNS is disabled by default (although there are valid reasons for that).

Setting NeutronDhcpAgentDnsmasqDnsServers fixes the problem because it also turns on the default Neutron DNS server, but I believe the drawback is you lose the internal name resolution because it's now forwarding requests to the specified external servers instead of the internal one that has the Neutron-specific entries. I should caveat that by saying I haven't actually experimented with this parameter because I don't think it does what I wanted, but this is my understanding of how it works based on my reading of the Neutron docs.

As far as defaulting NeutronDhcpAgentDnsmasqDnsServers to DnsServers when it is unset, the only concern I would have there is it might give VMs access to infrastructure DNS entries that they shouldn't have. I'm not sure how serious a problem that is, but it's a big part of the reason Neutron internal DNS is disabled by default. Ideally deployers should understand the implications before turning these options on.

Of course, I turned it on by default when Designate is in use so I can't really criticize anyone else doing the same. :-) I needed a recursive DNS server that was not the Designate BIND and the Neutron one was easiest to deploy. I should probably document the alternatives though.

**Comment by hardys** [comment]
@cybertron thanks very much for the feedback! :cake: 

Yeah I forgot DnsServers is only for the baremetal dns config, and in this case it's standalone tripleo so there's only one node, and we can't set --dns-nameserver on the undercloud ctlplane network & rely on routing dns via the undercloud either.

So I think probably setting NeutronDhcpAgentDnsmasqDnsServers explicitly until we re-enable designate is reasonable, but I'll wait on @tomassedovic for feedback.

Note this is only for dev/test setups doing OpenShift/OpenStack testing so probably we don't have to worry too much about restricting the DNS names exposed to the VMs in this case.

**Comment by flaper87** [comment]
> So I think probably setting NeutronDhcpAgentDnsmasqDnsServers explicitly until we re-enable designate is reasonable, but I'll wait on @tomassedovic for feedback.

I think this is prob the right solution. I haven't tested it so I'll wait on @tomassedovic for feedback too as I don't want to compromise my env right now.

**Comment by tomassedovic** [comment]
My environment's currently busted and I can't test anything. Please don't wait on me.

Yeah looks like setting `NeutronDhcpAgentDnsmasqDnsServers` the right way to go here, but I can't test it right now.

**Comment by celebdor** [comment]
@hardys I actually only removed https://github.com/imain/ocp-doit/pull/9/files#diff-1bbca4f10084e5e146e5ce9b0429747eL56

**Pull request merged**
